// Code generated by "stringer -type=SeqOrder"; DO NOT EDIT.

package main

import (
	"errors"
	"strconv"
)

var _ = errors.New("dummy error")

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FixedOrder-0]
	_ = x[RandomOrder-1]
	_ = x[CycleOrder-2]
	_ = x[SeqOrderN-3]
}

const _SeqOrder_name = "FixedOrderRandomOrderCycleOrderSeqOrderN"

var _SeqOrder_index = [...]uint8{0, 10, 21, 31, 40}

func (i SeqOrder) String() string {
	if i < 0 || i >= SeqOrder(len(_SeqOrder_index)-1) {
		return "SeqOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SeqOrder_name[_SeqOrder_index[i]:_SeqOrder_index[i+1]]
}

func (i *SeqOrder) FromString(s string) error {
	for j := 0; j < len(_SeqOrder_index)-1; j++ {
		if s == _SeqOrder_name[_SeqOrder_index[j]:_SeqOrder_index[j+1]] {
			*i = SeqOrder(j)
			return nil
		}
	}
	return errors.New("String: " + s + " is not a valid option for type: SeqOrder")
}
